###############################################################
#
# Project:
# Deep Sequential Learning under
# No-Arbitrage Affine Term Structure Models
#
# File:
# 05A_transformer_encoder.R
#
# Purpose:
#   Construct and validate a Keras 3 Transformer encoder
#   for the leakage-controlled sequential Treasury-yield
#   feature data generated by 04_sequence_generation.R.
#
# Architecture:
#
#   Input sequence
#        |
#        v
#   Feature Projection
#        |
#        v
#   Sinusoidal Positional Encoding
#        |
#        v
#   Transformer Encoder Block 1
#        |
#        v
#   Transformer Encoder Block 2
#        |
#        v
#   Sequence Representation
#
# Important:
#   - Input features are already scaled in 04_sequence_generation.R.
#   - Scaling parameters are estimated from training observations only.
#   - This script does NOT refit or modify feature scaling.
#   - Transformer output remains sequence-valued:
#
#       samples x time steps x attention_dim
#
###############################################################

rm(list = ls())

###############################################################
# 0. PACKAGES
###############################################################

required_packages <- c(
  "keras3",
  "tensorflow"
)

for (pkg in required_packages) {
  
  if (!requireNamespace(pkg, quietly = TRUE)) {
    
    install.packages(pkg)
    
  }
  
  library(
    pkg,
    character.only = TRUE
  )
}

###############################################################
# 1. TENSORFLOW SETTINGS
###############################################################

Sys.setenv(
  CUDA_VISIBLE_DEVICES = ""
)

Sys.setenv(
  TF_CPP_MIN_LOG_LEVEL = "2"
)

###############################################################
# 2. REPRODUCIBILITY
###############################################################

set.seed(123)

###############################################################
# 3. SETTINGS
###############################################################

SEQUENCE_FILE <- "04_SequenceData.RData"

MODEL_FILE <- "TransformerEncoder.keras"

CONFIG_FILE <- "05A_TransformerConfig.RData"

DIMENSION_FILE <- "05A_Transformer_Model_Dimensions.csv"

PE_FILE <- "05A_Positional_Encoding.csv"

VALIDATION_FILE <- "05A_Transformer_Validation.csv"

###############################################################
# 4. MODEL HYPERPARAMETERS
###############################################################

head_size <- 16L

num_heads <- 4L

ff_dim <- 128L

dropout <- 0.10

num_blocks <- 2L

###############################################################
# 5. LOAD SEQUENCE DATA
###############################################################

if (!file.exists(SEQUENCE_FILE)) {
  
  stop(
    paste0(
      SEQUENCE_FILE,
      " was not found in the current working directory.\n",
      "Current working directory: ",
      getwd(),
      "\n",
      "Please run 04_sequence_generation.R first."
    )
  )
}

sequence_env <- new.env(parent = emptyenv())

load(
  SEQUENCE_FILE,
  envir = sequence_env
)

###############################################################
# 6. REQUIRED OBJECTS FROM 04_SEQUENCE_GENERATION.R
###############################################################

required_objects <- c(
  
  "X_train",
  "X_valid",
  "X_test",
  
  "Y_factor_train",
  "Y_factor_valid",
  "Y_factor_test",
  
  "Y_yield_train",
  "Y_yield_valid",
  "Y_yield_test",
  
  "Y_yield_prev_train",
  "Y_yield_prev_valid",
  "Y_yield_prev_test",
  
  "Y_vol_train",
  "Y_vol_valid",
  "Y_vol_test",
  
  "YIELD_NAMES",
  "FACTOR_NAMES",
  
  "feature_scaled",
  "feature_center",
  "feature_scale",
  
  "WINDOW_SIZE",
  "FORECAST_HORIZON",
  
  "TRAIN_PROP",
  "VALID_PROP",
  "TEST_PROP"
  
)

missing_objects <- required_objects[
  !vapply(
    required_objects,
    exists,
    logical(1),
    envir = sequence_env,
    inherits = FALSE
  )
]

if (length(missing_objects) > 0) {
  
  stop(
    paste0(
      "The following required object(s) are missing from ",
      SEQUENCE_FILE,
      ":\n",
      paste(
        missing_objects,
        collapse = ", "
      ),
      "\n\nPlease rerun 04_sequence_generation.R."
    )
  )
}

###############################################################
# 7. EXTRACT OBJECTS
###############################################################

X_train <- sequence_env$X_train

X_valid <- sequence_env$X_valid

X_test <- sequence_env$X_test

Y_factor_train <- sequence_env$Y_factor_train

Y_factor_valid <- sequence_env$Y_factor_valid

Y_factor_test <- sequence_env$Y_factor_test

Y_yield_train <- sequence_env$Y_yield_train

Y_yield_valid <- sequence_env$Y_yield_valid

Y_yield_test <- sequence_env$Y_yield_test

Y_yield_prev_train <- sequence_env$Y_yield_prev_train

Y_yield_prev_valid <- sequence_env$Y_yield_prev_valid

Y_yield_prev_test <- sequence_env$Y_yield_prev_test

Y_vol_train <- sequence_env$Y_vol_train

Y_vol_valid <- sequence_env$Y_vol_valid

Y_vol_test <- sequence_env$Y_vol_test

YIELD_NAMES <- sequence_env$YIELD_NAMES

FACTOR_NAMES <- sequence_env$FACTOR_NAMES

feature_scaled <- sequence_env$feature_scaled

feature_center <- sequence_env$feature_center

feature_scale <- sequence_env$feature_scale

WINDOW_SIZE <- sequence_env$WINDOW_SIZE

FORECAST_HORIZON <- sequence_env$FORECAST_HORIZON

TRAIN_PROP <- sequence_env$TRAIN_PROP

VALID_PROP <- sequence_env$VALID_PROP

TEST_PROP <- sequence_env$TEST_PROP

###############################################################
# 8. BASIC SEQUENCE-DATA VALIDATION
###############################################################

if (!is.array(X_train) || length(dim(X_train)) != 3L) {
  
  stop(
    "X_train must be a 3-dimensional array: ",
    "samples x time steps x features."
  )
}

if (!is.array(X_valid) || length(dim(X_valid)) != 3L) {
  
  stop(
    "X_valid must be a 3-dimensional array."
  )
}

if (!is.array(X_test) || length(dim(X_test)) != 3L) {
  
  stop(
    "X_test must be a 3-dimensional array."
  )
}

###############################################################
# 9. INFER INPUT DIMENSIONS
###############################################################

n_train <- dim(X_train)[1]

n_valid <- dim(X_valid)[1]

n_test <- dim(X_test)[1]

sequence_length <- dim(X_train)[2]

feature_dim <- dim(X_train)[3]

###############################################################
# 10. DIMENSION CONSISTENCY
###############################################################

if (dim(X_valid)[1] < 1L) {
  
  stop(
    "X_valid contains no sequences."
  )
}

if (dim(X_test)[1] < 1L) {
  
  stop(
    "X_test contains no sequences."
  )
}

if (dim(X_valid)[2] != sequence_length) {
  
  stop(
    "X_valid has a different sequence length."
  )
}

if (dim(X_test)[2] != sequence_length) {
  
  stop(
    "X_test has a different sequence length."
  )
}

if (dim(X_valid)[3] != feature_dim) {
  
  stop(
    "X_valid has a different feature dimension."
  )
}

if (dim(X_test)[3] != feature_dim) {
  
  stop(
    "X_test has a different feature dimension."
  )
}

###############################################################
# 11. CHECK EXPECTED WINDOW SIZE
###############################################################

if (sequence_length != WINDOW_SIZE) {
  
  stop(
    paste0(
      "X_train sequence length (",
      sequence_length,
      ") does not match WINDOW_SIZE (",
      WINDOW_SIZE,
      ")."
    )
  )
}

###############################################################
# 12. NUMERIC / FINITE VALIDATION
###############################################################

check_numeric_finite <- function(
    x,
    object_name
) {
  
  if (!is.numeric(x)) {
    
    stop(
      object_name,
      " must be numeric."
    )
  }
  
  if (any(!is.finite(x))) {
    
    stop(
      object_name,
      " contains NA, NaN, or Inf values."
    )
  }
  
  invisible(TRUE)
}

check_numeric_finite(
  X_train,
  "X_train"
)

check_numeric_finite(
  X_valid,
  "X_valid"
)

check_numeric_finite(
  X_test,
  "X_test"
)

check_numeric_finite(
  Y_factor_train,
  "Y_factor_train"
)

check_numeric_finite(
  Y_factor_valid,
  "Y_factor_valid"
)

check_numeric_finite(
  Y_factor_test,
  "Y_factor_test"
)

check_numeric_finite(
  Y_yield_train,
  "Y_yield_train"
)

check_numeric_finite(
  Y_yield_valid,
  "Y_yield_valid"
)

check_numeric_finite(
  Y_yield_test,
  "Y_yield_test"
)

check_numeric_finite(
  Y_yield_prev_train,
  "Y_yield_prev_train"
)

check_numeric_finite(
  Y_yield_prev_valid,
  "Y_yield_prev_valid"
)

check_numeric_finite(
  Y_yield_prev_test,
  "Y_yield_prev_test"
)

check_numeric_finite(
  Y_vol_train,
  "Y_vol_train"
)

check_numeric_finite(
  Y_vol_valid,
  "Y_vol_valid"
)

check_numeric_finite(
  Y_vol_test,
  "Y_vol_test"
)

###############################################################
# 13. TARGET DIMENSION VALIDATION
###############################################################

if (ncol(Y_factor_train) != length(FACTOR_NAMES)) {
  
  stop(
    "Y_factor_train does not match FACTOR_NAMES."
  )
}

if (ncol(Y_factor_valid) != length(FACTOR_NAMES)) {
  
  stop(
    "Y_factor_valid does not match FACTOR_NAMES."
  )
}

if (ncol(Y_factor_test) != length(FACTOR_NAMES)) {
  
  stop(
    "Y_factor_test does not match FACTOR_NAMES."
  )
}

if (ncol(Y_yield_train) != length(YIELD_NAMES)) {
  
  stop(
    "Y_yield_train does not match YIELD_NAMES."
  )
}

if (ncol(Y_yield_valid) != length(YIELD_NAMES)) {
  
  stop(
    "Y_yield_valid does not match YIELD_NAMES."
  )
}

if (ncol(Y_yield_test) != length(YIELD_NAMES)) {
  
  stop(
    "Y_yield_test does not match YIELD_NAMES."
  )
}

if (ncol(Y_yield_prev_train) != length(YIELD_NAMES)) {
  
  stop(
    "Y_yield_prev_train does not match YIELD_NAMES."
  )
}

if (ncol(Y_yield_prev_valid) != length(YIELD_NAMES)) {
  
  stop(
    "Y_yield_prev_valid does not match YIELD_NAMES."
  )
}

if (ncol(Y_yield_prev_test) != length(YIELD_NAMES)) {
  
  stop(
    "Y_yield_prev_test does not match YIELD_NAMES."
  )
}

###############################################################
# 14. FEATURE-SCALING VALIDATION
###############################################################
#
# 04_sequence_generation.R is responsible for fitting the
# feature scaler using training observations only.
#
# This script only verifies that the saved scaling objects
# are valid and does not refit them.
#
###############################################################

if (length(feature_center) != feature_dim) {
  
  stop(
    "feature_center length does not match feature dimension."
  )
}

if (length(feature_scale) != feature_dim) {
  
  stop(
    "feature_scale length does not match feature dimension."
  )
}

if (any(!is.finite(feature_center))) {
  
  stop(
    "feature_center contains non-finite values."
  )
}

if (any(!is.finite(feature_scale))) {
  
  stop(
    "feature_scale contains non-finite values."
  )
}

if (any(feature_scale <= 0)) {
  
  stop(
    "feature_scale must contain strictly positive values."
  )
}

###############################################################
# 15. MODEL PARAMETER VALIDATION
###############################################################

if (sequence_length < 1L) {
  
  stop(
    "sequence_length must be positive."
  )
}

if (feature_dim < 1L) {
  
  stop(
    "feature_dim must be positive."
  )
}

if (head_size < 1L) {
  
  stop(
    "head_size must be positive."
  )
}

if (num_heads < 1L) {
  
  stop(
    "num_heads must be positive."
  )
}

if (ff_dim < 1L) {
  
  stop(
    "ff_dim must be positive."
  )
}

if (
  !is.numeric(dropout) ||
  length(dropout) != 1L ||
  !is.finite(dropout) ||
  dropout < 0 ||
  dropout >= 1
) {
  
  stop(
    "dropout must satisfy 0 <= dropout < 1."
  )
}

if (num_blocks < 1L) {
  
  stop(
    "num_blocks must be at least 1."
  )
}

###############################################################
# 16. ATTENTION DIMENSION
###############################################################
#
# Multi-head attention uses:
#
#     attention_dim = head_size * num_heads
#
# Therefore:
#
#     attention_dim = 16 * 4 = 64
#
# The original feature dimension does not need to equal 64.
# The FeatureProjection layer maps the input feature space
# into the Transformer embedding space.
#
###############################################################

attention_dim <-
  head_size *
  num_heads

###############################################################
# 17. INFORMATION
###############################################################

cat("\n")
cat("============================================================\n")
cat("TRANSFORMER ENCODER SETUP\n")
cat("============================================================\n")

cat(
  "Working directory: ",
  getwd(),
  "\n",
  sep = ""
)

cat(
  "Sequence data file: ",
  SEQUENCE_FILE,
  "\n",
  sep = ""
)

cat(
  "Training sequences: ",
  n_train,
  "\n",
  sep = ""
)

cat(
  "Validation sequences: ",
  n_valid,
  "\n",
  sep = ""
)

cat(
  "Testing sequences: ",
  n_test,
  "\n",
  sep = ""
)

cat(
  "Sequence length: ",
  sequence_length,
  "\n",
  sep = ""
)

cat(
  "Input feature dimension: ",
  feature_dim,
  "\n",
  sep = ""
)

cat(
  "Attention head size: ",
  head_size,
  "\n",
  sep = ""
)

cat(
  "Number of attention heads: ",
  num_heads,
  "\n",
  sep = ""
)

cat(
  "Attention embedding dimension: ",
  attention_dim,
  "\n",
  sep = ""
)

cat(
  "Feed-forward dimension: ",
  ff_dim,
  "\n",
  sep = ""
)

cat(
  "Dropout: ",
  dropout,
  "\n",
  sep = ""
)

cat(
  "Transformer blocks: ",
  num_blocks,
  "\n",
  sep = ""
)

cat("============================================================\n")

###############################################################
# 18. POSITIONAL ENCODING
###############################################################
#
# Standard sinusoidal positional encoding:
#
#   PE(pos, 2i)   = sin(pos / 10000^(2i/d))
#   PE(pos, 2i+1) = cos(pos / 10000^(2i/d))
#
# The resulting matrix has dimension:
#
#   sequence_length x attention_dim
#
###############################################################

positional_encoding <- function(
    sequence_length,
    d_model
) {
  
  if (sequence_length < 1L) {
    
    stop(
      "sequence_length must be positive."
    )
  }
  
  if (d_model < 2L) {
    
    stop(
      "d_model must be at least 2."
    )
  }
  
  position <- matrix(
    rep(
      0:(sequence_length - 1L),
      d_model
    ),
    nrow = sequence_length,
    ncol = d_model
  )
  
  even_index <- seq(
    0L,
    d_model - 1L,
    by = 2L
  )
  
  odd_index <- seq(
    1L,
    d_model - 1L,
    by = 2L
  )
  
  div_term <- exp(
    even_index *
      (
        -log(10000) /
          d_model
      )
  )
  
  PE <- matrix(
    0,
    nrow = sequence_length,
    ncol = d_model
  )
  
  PE[
    ,
    even_index + 1L
  ] <-
    sin(
      position[
        ,
        even_index + 1L
      ] *
        rep(
          div_term,
          each = sequence_length
        )
    )
  
  if (length(odd_index) > 0L) {
    
    PE[
      ,
      odd_index + 1L
    ] <-
      cos(
        position[
          ,
          odd_index + 1L
        ] *
          rep(
            div_term[
              seq_along(odd_index)
            ],
            each = sequence_length
          )
      )
  }
  
  PE
}

###############################################################
# 19. CREATE POSITIONAL ENCODING
###############################################################

PE_matrix <-
  positional_encoding(
    sequence_length =
      sequence_length,
    d_model =
      attention_dim
  )

PE_tensor <-
  tf$constant(
    PE_matrix,
    dtype = tf$float32
  )

###############################################################
# 20. POSITIONAL ENCODING VALIDATION
###############################################################

if (!is.matrix(PE_matrix)) {
  
  stop(
    "PE_matrix must be a matrix."
  )
}

if (
  nrow(PE_matrix) != sequence_length ||
  ncol(PE_matrix) != attention_dim
) {
  
  stop(
    "Positional encoding has incorrect dimensions."
  )
}

if (any(!is.finite(PE_matrix))) {
  
  stop(
    "Positional encoding contains non-finite values."
  )
}

###############################################################
# 21. TRANSFORMER ENCODER BLOCK
###############################################################

transformer_block <- function(
    
  inputs,
  
  attention_dim,
  
  head_size = 16L,
  
  num_heads = 4L,
  
  ff_dim = 128L,
  
  dropout = 0.10,
  
  block_id = 1L
  
) {
  
  ###########################################################
  # Multi-Head Self-Attention
  ###########################################################
  
  attention_layer <-
    layer_multi_head_attention(
      
      num_heads =
        num_heads,
      
      key_dim =
        head_size,
      
      dropout =
        dropout,
      
      name =
        paste0(
          "SelfAttention_",
          block_id
        )
    )
  
  attention <-
    attention_layer(
      query = inputs,
      key = inputs,
      value = inputs
    )
  
  ###########################################################
  # Attention Dropout
  ###########################################################
  
  attention <-
    layer_dropout(
      rate = dropout,
      name =
        paste0(
          "AttentionDropout_",
          block_id
        )
    )(
      attention
    )
  
  ###########################################################
  # First Residual Connection
  ###########################################################
  
  x <-
    layer_add(
      list(
        inputs,
        attention
      ),
      name =
        paste0(
          "AttentionResidual_",
          block_id
        )
    )
  
  ###########################################################
  # First Layer Normalization
  ###########################################################
  
  x <-
    layer_layer_normalization(
      epsilon = 1e-6,
      name =
        paste0(
          "AttentionNorm_",
          block_id
        )
    )(
      x
    )
  
  ###########################################################
  # Feed-Forward Network
  ###########################################################
  
  ff <-
    x %>%
    
    layer_dense(
      units = ff_dim,
      activation = "relu",
      name =
        paste0(
          "FFN_Dense1_",
          block_id
        )
    ) %>%
    
    layer_dropout(
      rate = dropout,
      name =
        paste0(
          "FFN_Dropout_",
          block_id
        )
    ) %>%
    
    layer_dense(
      units = attention_dim,
      name =
        paste0(
          "FFN_Dense2_",
          block_id
        )
    )
  
  ###########################################################
  # Second Residual Connection
  ###########################################################
  
  x <-
    layer_add(
      list(
        x,
        ff
      ),
      name =
        paste0(
          "FFNResidual_",
          block_id
        )
    )
  
  ###########################################################
  # Second Layer Normalization
  ###########################################################
  
  outputs <-
    layer_layer_normalization(
      epsilon = 1e-6,
      name =
        paste0(
          "FFNNorm_",
          block_id
        )
    )(
      x
    )
  
  outputs
}

###############################################################
# 22. BUILD TRANSFORMER ENCODER
###############################################################

build_transformer_encoder <- function(
    
  sequence_length,
  
  feature_dim,
  
  attention_dim,
  
  head_size = 16L,
  
  num_heads = 4L,
  
  ff_dim = 128L,
  
  dropout = 0.10,
  
  num_blocks = 2L
  
) {
  
  ###########################################################
  # Input
  ###########################################################
  
  inputs <-
    layer_input(
      
      shape =
        c(
          sequence_length,
          feature_dim
        ),
      
      name =
        "InputSequence"
    )
  
  ###########################################################
  # Input Projection
  ###########################################################
  
  x <-
    inputs %>%
    
    layer_dense(
      
      units =
        attention_dim,
      
      name =
        "FeatureProjection"
    )
  
  ###########################################################
  # Sinusoidal Positional Encoding
  ###########################################################
  #
  # PE_tensor has shape:
  #
  #   sequence_length x attention_dim
  #
  # TensorFlow broadcasts it across the batch dimension.
  #
  ###########################################################
  
  x <-
    layer_lambda(
      
      f = function(z) {
        
        z + PE_tensor
        
      },
      
      name =
        "PositionalEncoding"
    )(
      x
    )
  
  ###########################################################
  # Transformer Encoder Blocks
  ###########################################################
  
  for (b in seq_len(num_blocks)) {
    
    x <-
      transformer_block(
        
        inputs =
          x,
        
        attention_dim =
          attention_dim,
        
        head_size =
          head_size,
        
        num_heads =
          num_heads,
        
        ff_dim =
          ff_dim,
        
        dropout =
          dropout,
        
        block_id =
          b
      )
  }
  
  ###########################################################
  # Encoder Model
  ###########################################################
  
  keras_model(
    
    inputs =
      inputs,
    
    outputs =
      x,
    
    name =
      "TransformerEncoder"
  )
}

###############################################################
# 23. BUILD MODEL
###############################################################

encoder <-
  build_transformer_encoder(
    
    sequence_length =
      sequence_length,
    
    feature_dim =
      feature_dim,
    
    attention_dim =
      attention_dim,
    
    head_size =
      head_size,
    
    num_heads =
      num_heads,
    
    ff_dim =
      ff_dim,
    
    dropout =
      dropout,
    
    num_blocks =
      num_blocks
  )

###############################################################
# 24. MODEL SUMMARY
###############################################################

cat("\n")
cat("============================================================\n")
cat("TRANSFORMER ENCODER SUMMARY\n")
cat("============================================================\n")

print(
  summary(
    encoder
  )
)

###############################################################
# 25. MODEL INPUT / OUTPUT SHAPES
###############################################################

cat("\n")
cat("============================================================\n")
cat("MODEL DIMENSIONS\n")
cat("============================================================\n")

cat(
  "Input shape:\n"
)

print(
  encoder$input_shape
)

cat(
  "Output shape:\n"
)

print(
  encoder$output_shape
)

###############################################################
# 26. FORWARD-PASS TEST
###############################################################

cat("\n")
cat("============================================================\n")
cat("FORWARD-PASS TEST\n")
cat("============================================================\n")

test_batch_size <-
  min(
    2L,
    n_train
  )

if (test_batch_size < 1L) {
  
  stop(
    "Training set contains no sequences."
  )
}

X_test_batch <-
  X_train[
    seq_len(test_batch_size),
    ,
    ,
    drop = FALSE
  ]

###############################################################
# 27. ENSURE NUMERIC ARRAY
###############################################################

X_test_batch <-
  array(
    as.numeric(X_test_batch),
    dim =
      dim(X_test_batch)
  )

if (any(!is.finite(X_test_batch))) {
  
  stop(
    "Forward-pass test batch contains non-finite values."
  )
}

###############################################################
# 28. FORWARD PASS
###############################################################

test_output <-
  encoder(
    X_test_batch,
    training = FALSE
  )

###############################################################
# 29. OUTPUT SHAPE
###############################################################

output_shape <-
  dim(
    test_output
  )

cat(
  "Forward-pass output shape:\n"
)

print(
  output_shape
)

###############################################################
# 30. OUTPUT DIMENSION VALIDATION
###############################################################

expected_output_dim <-
  c(
    test_batch_size,
    sequence_length,
    attention_dim
  )

if (!identical(
  as.integer(output_shape),
  as.integer(expected_output_dim)
)) {
  
  stop(
    paste0(
      "Unexpected Transformer output shape.\n",
      "Expected: ",
      paste(
        expected_output_dim,
        collapse = " x "
      ),
      "\nObserved: ",
      paste(
        output_shape,
        collapse = " x "
      )
    )
  )
}

###############################################################
# 31. OUTPUT FINITE CHECK
###############################################################

test_output_array <-
  as.array(
    test_output
  )

if (any(!is.finite(test_output_array))) {
  
  stop(
    "Transformer forward pass produced non-finite values."
  )
}

cat(
  "Forward pass successful.\n"
)

cat(
  "Output dimension: ",
  paste(
    output_shape,
    collapse = " x "
  ),
  "\n",
  sep = ""
)

###############################################################
# 32. MODEL PARAMETER COUNT
###############################################################

parameter_count <-
  tryCatch(
    
    as.numeric(
      encoder$count_params()
    ),
    
    error = function(e) {
      
      NA_real_
      
    }
  )

###############################################################
# 33. SAVE KERAS 3 MODEL
###############################################################

cat("\n")
cat(
  "Saving Transformer model to:\n"
)

cat(
  MODEL_FILE,
  "\n"
)

save_model(
  encoder,
  MODEL_FILE,
  overwrite = TRUE
)

###############################################################
# 34. VERIFY MODEL FILE
###############################################################

if (!file.exists(MODEL_FILE)) {
  
  stop(
    "Transformer model was not saved successfully."
  )
}

model_size <-
  file.info(
    MODEL_FILE
  )$size

if (
  is.na(model_size) ||
  model_size <= 0
) {
  
  stop(
    "Transformer model file is empty."
  )
}

cat(
  "Model saved successfully.\n"
)

cat(
  "Model file size: ",
  round(
    model_size / 1024^2,
    3
  ),
  " MB\n",
  sep = ""
)

###############################################################
# 35. SAVE MODEL CONFIGURATION
###############################################################

TransformerConfig <- list(
  
  model_name =
    "TransformerEncoder",
  
  sequence_length =
    sequence_length,
  
  feature_dim =
    feature_dim,
  
  attention_dim =
    attention_dim,
  
  head_size =
    head_size,
  
  num_heads =
    num_heads,
  
  ff_dim =
    ff_dim,
  
  dropout =
    dropout,
  
  num_blocks =
    num_blocks,
  
  input_shape =
    c(
      sequence_length,
      feature_dim
    ),
  
  output_shape =
    c(
      sequence_length,
      attention_dim
    ),
  
  training_sequences =
    n_train,
  
  validation_sequences =
    n_valid,
  
  testing_sequences =
    n_test,
  
  window_size =
    WINDOW_SIZE,
  
  forecast_horizon =
    FORECAST_HORIZON,
  
  train_prop =
    TRAIN_PROP,
  
  valid_prop =
    VALID_PROP,
  
  test_prop =
    TEST_PROP,
  
  yield_names =
    YIELD_NAMES,
  
  factor_names =
    FACTOR_NAMES,
  
  parameter_count =
    parameter_count,
  
  model_file =
    MODEL_FILE,
  
  sequence_data_file =
    SEQUENCE_FILE,
  
  scaling_source =
    "04_sequence_generation.R",
  
  scaling_policy =
    "Training observations only; frozen for validation and test."
  
)

save(
  TransformerConfig,
  file = CONFIG_FILE
)

###############################################################
# 36. SAVE MODEL DIMENSIONS
###############################################################

model_dimensions <-
  data.frame(
    
    Parameter = c(
      
      "Training samples",
      
      "Validation samples",
      
      "Testing samples",
      
      "Sequence length",
      
      "Input feature dimension",
      
      "Attention embedding dimension",
      
      "Head size",
      
      "Number of heads",
      
      "Feed-forward dimension",
      
      "Dropout",
      
      "Transformer blocks",
      
      "Forecast horizon",
      
      "Number of model parameters"
      
    ),
    
    Value = c(
      
      n_train,
      
      n_valid,
      
      n_test,
      
      sequence_length,
      
      feature_dim,
      
      attention_dim,
      
      head_size,
      
      num_heads,
      
      ff_dim,
      
      dropout,
      
      num_blocks,
      
      FORECAST_HORIZON,
      
      parameter_count
      
    ),
    
    stringsAsFactors = FALSE
    
  )

write.csv(
  
  model_dimensions,
  
  DIMENSION_FILE,
  
  row.names = FALSE
  
)

###############################################################
# 37. SAVE POSITIONAL ENCODING
###############################################################

write.csv(
  
  PE_matrix,
  
  PE_FILE,
  
  row.names = FALSE
  
)

###############################################################
# 38. SAVE MODEL VALIDATION RESULTS
###############################################################

validation_results <-
  data.frame(
    
    Check = c(
      
      "X_train is 3-dimensional",
      
      "X_valid is 3-dimensional",
      
      "X_test is 3-dimensional",
      
      "Training data finite",
      
      "Validation data finite",
      
      "Testing data finite",
      
      "Feature scaler valid",
      
      "Target dimensions valid",
      
      "Forward pass successful",
      
      "Output dimension correct",
      
      "Output finite",
      
      "Model file exists",
      
      "Model file non-empty"
      
    ),
    
    Result = c(
      
      length(dim(X_train)) == 3L,
      
      length(dim(X_valid)) == 3L,
      
      length(dim(X_test)) == 3L,
      
      all(is.finite(X_train)),
      
      all(is.finite(X_valid)),
      
      all(is.finite(X_test)),
      
      all(is.finite(feature_center)) &&
        all(is.finite(feature_scale)) &&
        all(feature_scale > 0),
      
      ncol(Y_factor_train) ==
        length(FACTOR_NAMES) &&
        ncol(Y_yield_train) ==
        length(YIELD_NAMES) &&
        ncol(Y_yield_prev_train) ==
        length(YIELD_NAMES),
      
      TRUE,
      
      identical(
        as.integer(output_shape),
        as.integer(expected_output_dim)
      ),
      
      all(is.finite(test_output_array)),
      
      file.exists(MODEL_FILE),
      
      !is.na(model_size) &&
        model_size > 0
      
    ),
    
    stringsAsFactors = FALSE
    
  )

write.csv(
  
  validation_results,
  
  VALIDATION_FILE,
  
  row.names = FALSE
  
)

###############################################################
# 39. FINAL VALIDATION
###############################################################

if (!all(validation_results$Result)) {
  
  stop(
    "One or more Transformer validation checks failed."
  )
}

###############################################################
# 40. FINAL SUMMARY
###############################################################

cat("\n")
cat("============================================================\n")
cat("TRANSFORMER ENCODER CREATED SUCCESSFULLY\n")
cat("============================================================\n")

cat(
  "Input sequence length: ",
  sequence_length,
  "\n",
  sep = ""
)

cat(
  "Input feature dimension: ",
  feature_dim,
  "\n",
  sep = ""
)

cat(
  "Attention embedding dimension: ",
  attention_dim,
  "\n",
  sep = ""
)

cat(
  "Attention head size: ",
  head_size,
  "\n",
  sep = ""
)

cat(
  "Attention heads: ",
  num_heads,
  "\n",
  sep = ""
)

cat(
  "Feed-forward dimension: ",
  ff_dim,
  "\n",
  sep = ""
)

cat(
  "Transformer blocks: ",
  num_blocks,
  "\n",
  sep = ""
)

cat(
  "Dropout: ",
  dropout,
  "\n",
  sep = ""
)

cat(
  "Model parameters: ",
  parameter_count,
  "\n",
  sep = ""
)

cat("\n")

cat(
  "Saved model: ",
  MODEL_FILE,
  "\n",
  sep = ""
)

cat(
  "Saved configuration: ",
  CONFIG_FILE,
  "\n",
  sep = ""
)

cat(
  "Saved dimensions: ",
  DIMENSION_FILE,
  "\n",
  sep = ""
)

cat(
  "Saved positional encoding: ",
  PE_FILE,
  "\n",
  sep = ""
)

cat(
  "Saved validation report: ",
  VALIDATION_FILE,
  "\n",
  sep = ""
)

cat("\n")

cat(
  "Input scaling source: 04_sequence_generation.R\n"
)

cat(
  "Scaling policy: training observations only.\n"
)

cat(
  "Transformer encoder output: samples x time steps x ",
  attention_dim,
  "\n",
  sep = ""
)

cat("\n")
cat(
  "05A_transformer_encoder.R completed successfully.\n"
)
cat("============================================================\n")