###############################################################
#
# Project:
# Deep Sequential Learning with Adaptive Sampling under
# No-Arbitrage Affine Term Structure Models
#
# File:
# 05D_compile_model.R
#
# Purpose:
#   Build and compile the complete deep sequential model using
#   the sequence data generated by 04_sequence_generation.R.
#
# Data structure:
#
#   X:
#       samples x 20 time steps x 55 features
#
#   Affine factors:
#       Level
#       Slope
#
#   Treasury yields:
#       DGS10
#       DTB3
#
#   Volatility:
#       RMS daily yield change
#
# Outputs:
#
#   Affine_Factors : 2
#   Affine_Pricing : 2
#   Volatility     : 1
#
###############################################################


###############################################################
# 0. PACKAGES
###############################################################

required_packages <- c(
    "keras",
    "tensorflow"
)

for (pkg in required_packages) {

    if (!requireNamespace(pkg, quietly = TRUE)) {

        install.packages(pkg)

    }

    library(
        pkg,
        character.only = TRUE
    )
}


###############################################################
# 1. REPRODUCIBILITY
###############################################################

set.seed(123)

tf$random$set_seed(123L)


###############################################################
# 2. LOAD SEQUENCE DATA
###############################################################

sequence_file <- "04_SequenceData.RData"

if (!file.exists(sequence_file)) {

    stop(
        paste0(
            sequence_file,
            " was not found.\n",
            "Current working directory: ",
            getwd(),
            "\n",
            "Please place 04_SequenceData.RData in the project folder."
        )
    )
}

load(sequence_file)


###############################################################
# 3. CHECK REQUIRED OBJECTS
###############################################################

required_objects <- c(

    "X_train",
    "X_valid",
    "X_test",

    "Y_factor_train",
    "Y_factor_valid",
    "Y_factor_test",

    "Y_yield_train",
    "Y_yield_valid",
    "Y_yield_test",

    "Y_vol_train",
    "Y_vol_valid",
    "Y_vol_test"

)

missing_objects <-

    required_objects[
        !vapply(
            required_objects,
            exists,
            logical(1)
        )
    ]

if (length(missing_objects) > 0) {

    stop(
        paste0(
            "The following required objects are missing from ",
            sequence_file,
            ":\n",
            paste(
                missing_objects,
                collapse = ", "
            )
        )
    )
}


###############################################################
# 4. VERIFY INPUT STRUCTURE
###############################################################

if (length(dim(X_train)) != 3L) {

    stop(
        paste0(
            "X_train must be a 3-dimensional array:\n",
            "samples x time steps x features.\n",
            "Found dimensions: ",
            paste(
                dim(X_train),
                collapse = " x "
            )
        )
    )
}

if (length(dim(X_valid)) != 3L) {

    stop(
        "X_valid must be a 3-dimensional array."
    )
}

if (length(dim(X_test)) != 3L) {

    stop(
        "X_test must be a 3-dimensional array."
    )
}


###############################################################
# 5. INFER DIMENSIONS
###############################################################

n_train <- dim(X_train)[1]

sequence_length <- dim(X_train)[2]

feature_dim <- dim(X_train)[3]

n_factor_outputs <- ncol(Y_factor_train)

n_yield_outputs <- ncol(Y_yield_train)


###############################################################
# 6. EXPECTED TARGET STRUCTURE
###############################################################

expected_factor_names <- c(
    "Level",
    "Slope"
)

expected_yield_names <- c(
    "DGS10",
    "DTB3"
)


###############################################################
# 7. CHECK NUMBER OF FACTORS
###############################################################

if (
    n_factor_outputs !=
    length(expected_factor_names)
) {

    stop(
        paste0(
            "Expected exactly ",
            length(expected_factor_names),
            " affine factors, but found ",
            n_factor_outputs,
            ".\n",
            "Expected: Level, Slope."
        )
    )
}


###############################################################
# 8. CHECK NUMBER OF YIELDS
###############################################################

if (
    n_yield_outputs !=
    length(expected_yield_names)
) {

    stop(
        paste0(
            "Expected exactly ",
            length(expected_yield_names),
            " Treasury yields, but found ",
            n_yield_outputs,
            ".\n",
            "Expected: DGS10, DTB3."
        )
    )
}


###############################################################
# 9. TARGET NAMES
###############################################################

factor_names <- expected_factor_names

yield_names <- expected_yield_names


###############################################################
# Factor names
###############################################################

if (is.null(colnames(Y_factor_train))) {

    colnames(Y_factor_train) <- factor_names

}

if (is.null(colnames(Y_factor_valid))) {

    colnames(Y_factor_valid) <- factor_names

}

if (is.null(colnames(Y_factor_test))) {

    colnames(Y_factor_test) <- factor_names

}


###############################################################
# Verify factor ordering
###############################################################

if (
    !identical(
        colnames(Y_factor_train),
        factor_names
    )
) {

    stop(
        paste0(
            "Y_factor_train must contain:\n",
            "Level, Slope\n",
            "Found: ",
            paste(
                colnames(Y_factor_train),
                collapse = ", "
            )
        )
    )
}


###############################################################
# Yield names
###############################################################

if (is.null(colnames(Y_yield_train))) {

    colnames(Y_yield_train) <- yield_names

}

if (is.null(colnames(Y_yield_valid))) {

    colnames(Y_yield_valid) <- yield_names

}

if (is.null(colnames(Y_yield_test))) {

    colnames(Y_yield_test) <- yield_names

}


###############################################################
# Verify yield ordering
###############################################################

if (
    !identical(
        colnames(Y_yield_train),
        yield_names
    )
) {

    stop(
        paste0(
            "Y_yield_train must contain:\n",
            "DGS10, DTB3\n",
            "Found: ",
            paste(
                colnames(Y_yield_train),
                collapse = ", "
            )
        )
    )
}


###############################################################
# 10. CONVERT TARGETS TO NUMERIC
###############################################################

Y_factor_train <- as.matrix(Y_factor_train)

Y_factor_valid <- as.matrix(Y_factor_valid)

Y_factor_test <- as.matrix(Y_factor_test)


Y_yield_train <- as.matrix(Y_yield_train)

Y_yield_valid <- as.matrix(Y_yield_valid)

Y_yield_test <- as.matrix(Y_yield_test)


Y_vol_train <- as.numeric(Y_vol_train)

Y_vol_valid <- as.numeric(Y_vol_valid)

Y_vol_test <- as.numeric(Y_vol_test)


###############################################################
# 11. CHECK SAMPLE COUNTS
###############################################################

if (
    nrow(Y_factor_train) != n_train
) {

    stop(
        "X_train and Y_factor_train have different numbers of observations."
    )
}

if (
    nrow(Y_yield_train) != n_train
) {

    stop(
        "X_train and Y_yield_train have different numbers of observations."
    )
}

if (
    length(Y_vol_train) != n_train
) {

    stop(
        "X_train and Y_vol_train have different numbers of observations."
    )
}


###############################################################
# Validation sample counts
###############################################################

if (
    dim(X_valid)[1] != nrow(Y_factor_valid)
) {

    stop(
        "X_valid and Y_factor_valid have different numbers of observations."
    )
}

if (
    dim(X_valid)[1] != nrow(Y_yield_valid)
) {

    stop(
        "X_valid and Y_yield_valid have different numbers of observations."
    )
}

if (
    dim(X_valid)[1] != length(Y_vol_valid)
) {

    stop(
        "X_valid and Y_vol_valid have different numbers of observations."
    )
}


###############################################################
# Test sample counts
###############################################################

if (
    dim(X_test)[1] != nrow(Y_factor_test)
) {

    stop(
        "X_test and Y_factor_test have different numbers of observations."
    )
}

if (
    dim(X_test)[1] != nrow(Y_yield_test)
) {

    stop(
        "X_test and Y_yield_test have different numbers of observations."
    )
}

if (
    dim(X_test)[1] != length(Y_vol_test)
) {

    stop(
        "X_test and Y_vol_test have different numbers of observations."
    )
}


###############################################################
# 12. CHECK FINITE VALUES
###############################################################

if (any(!is.finite(X_train))) {

    stop(
        "X_train contains non-finite values."
    )
}

if (any(!is.finite(X_valid))) {

    stop(
        "X_valid contains non-finite values."
    )
}

if (any(!is.finite(X_test))) {

    stop(
        "X_test contains non-finite values."
    )
}

if (any(!is.finite(Y_factor_train))) {

    stop(
        "Y_factor_train contains non-finite values."
    )
}

if (any(!is.finite(Y_yield_train))) {

    stop(
        "Y_yield_train contains non-finite values."
    )
}

if (any(!is.finite(Y_vol_train))) {

    stop(
        "Y_vol_train contains non-finite values."
    )


}


###############################################################
# 13. MODEL HYPERPARAMETERS
###############################################################

head_size <- 32L

num_heads <- 4L

ff_dim <- 128L

dropout_transformer <- 0.10

num_transformer_blocks <- 2L

cnn_filters_1 <- 64L

cnn_filters_2 <- 128L

cnn_kernel_size <- 3L

dropout_cnn <- 0.15

lstm_units <- 64L

dense_units <- 128L

dropout_dense <- 0.20

learning_rate <- 0.0005


###############################################################
# 14. LOSS WEIGHTS
###############################################################

lambda_FACTOR <- 0.10

lambda_YIELD <- 1.00

lambda_VOL <- 0.05


###############################################################
# 15. DISPLAY DATA INFORMATION
###############################################################

cat("\n")
cat("============================================================\n")
cat("DEEP AFFINE TRANSFORMER MODEL\n")
cat("============================================================\n")

cat(
    "Training sequences : ",
    n_train,
    "\n",
    sep = ""
)

cat(
    "Validation sequences: ",
    dim(X_valid)[1],
    "\n",
    sep = ""
)

cat(
    "Testing sequences   : ",
    dim(X_test)[1],
    "\n",
    sep = ""
)

cat(
    "Sequence length     : ",
    sequence_length,
    "\n",
    sep = ""
)

cat(
    "Feature dimension   : ",
    feature_dim,
    "\n",
    sep = ""
)

cat(
    "Affine factors      : ",
    n_factor_outputs,
    "\n",
    sep = ""
)

cat(
    "Yield outputs       : ",
    n_yield_outputs,
    "\n",
    sep = ""
)

cat(
    "Factor names        : ",
    paste(
        factor_names,
        collapse = ", "
    ),
    "\n",
    sep = ""
)

cat(
    "Yield names         : ",
    paste(
        yield_names,
        collapse = ", "
    ),
    "\n",
    sep = ""
)


###############################################################
# 16. INPUT LAYER
###############################################################

inputs <-

    layer_input(

        shape = c(
            sequence_length,
            feature_dim
        ),

        name = "Yield_Macro_Input"
    )


###############################################################
# 17. INPUT PROJECTION
###############################################################

x <-

    inputs %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name = "Input_Projection"
    )


###############################################################
# 18. TRANSFORMER BLOCK 1
###############################################################

cat(
    "Building Transformer block 1...\n"
)

attention_1 <-

    layer_multi_head_attention(

        num_heads = num_heads,

        key_dim = head_size,

        dropout = dropout_transformer,

        name = "MultiHeadAttention_1"

    )(
        query = x,
        value = x,
        key = x
    )


###############################################################
# Attention residual
###############################################################

x1 <-

    layer_concatenate(

        axis = -1L,

        name =
            "TransformerResidualConcat_1"

    )(
        list(
            x,
            attention_1
        )
    )


x1 <-

    x1 %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name =
            "TransformerResidualProjection_1"

    ) %>%

    layer_layer_normalization(

        epsilon = 1e-6,

        name =
            "TransformerNorm_1"
    )


###############################################################
# Transformer FFN
###############################################################

ff1 <-

    x1 %>%

    layer_dense(

        units = ff_dim,

        activation = "relu",

        name =
            "TransformerFFN1_Dense1"
    ) %>%

    layer_dropout(

        rate =
            dropout_transformer,

        name =
            "TransformerFFN1_Dropout"
    ) %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name =
            "TransformerFFN1_Dense2"
    )


###############################################################
# FFN residual
###############################################################

x1 <-

    layer_concatenate(

        axis = -1L,

        name =
            "TransformerFFNResidualConcat_1"

    )(
        list(
            x1,
            ff1
        )
    )


x1 <-

    x1 %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name =
            "TransformerFFNResidualProjection_1"

    ) %>%

    layer_layer_normalization(

        epsilon = 1e-6,

        name =
            "TransformerFFNNorm_1"
    )


###############################################################
# 19. TRANSFORMER BLOCK 2
###############################################################

cat(
    "Building Transformer block 2...\n"
)

attention_2 <-

    layer_multi_head_attention(

        num_heads = num_heads,

        key_dim = head_size,

        dropout = dropout_transformer,

        name = "MultiHeadAttention_2"

    )(
        query = x1,
        value = x1,
        key = x1
    )


###############################################################
# Attention residual
###############################################################

x2 <-

    layer_concatenate(

        axis = -1L,

        name =
            "TransformerResidualConcat_2"

    )(
        list(
            x1,
            attention_2
        )
    )


x2 <-

    x2 %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name =
            "TransformerResidualProjection_2"

    ) %>%

    layer_layer_normalization(

        epsilon = 1e-6,

        name =
            "TransformerNorm_2"
    )


###############################################################
# Transformer FFN
###############################################################

ff2 <-

    x2 %>%

    layer_dense(

        units = ff_dim,

        activation = "relu",

        name =
            "TransformerFFN2_Dense1"
    ) %>%

    layer_dropout(

        rate =
            dropout_transformer,

        name =
            "TransformerFFN2_Dropout"
    ) %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name =
            "TransformerFFN2_Dense2"
    )


###############################################################
# FFN residual
###############################################################

x <-

    layer_concatenate(

        axis = -1L,

        name =
            "TransformerFFNResidualConcat_2"

    )(
        list(
            x2,
            ff2
        )
    )


x <-

    x %>%

    layer_dense(

        units = feature_dim,

        activation = "linear",

        name =
            "TransformerFFNResidualProjection_2"

    ) %>%

    layer_layer_normalization(

        epsilon = 1e-6,

        name =
            "TransformerFFNNorm_2"
    )


###############################################################
# 20. CNN FEATURE EXTRACTION
###############################################################

cat(
    "Building CNN layers...\n"
)

x <-

    x %>%

    layer_conv_1d(

        filters =
            cnn_filters_1,

        kernel_size =
            cnn_kernel_size,

        padding =
            "same",

        activation =
            "relu",

        name =
            "CNN_1"

    ) %>%

    layer_batch_normalization(

        name =
            "CNN_BatchNorm_1"

    ) %>%

    layer_dropout(

        rate =
            dropout_cnn,

        name =
            "CNN_Dropout_1"
    )


###############################################################
# CNN 2
###############################################################

x <-

    x %>%

    layer_conv_1d(

        filters =
            cnn_filters_2,

        kernel_size =
            cnn_kernel_size,

        padding =
            "same",

        activation =
            "relu",

        name =
            "CNN_2"

    ) %>%

    layer_batch_normalization(

        name =
            "CNN_BatchNorm_2"
    )


###############################################################
# 21. BIDIRECTIONAL LSTM
###############################################################

cat(
    "Building BiLSTM...\n"
)

x <-

    x %>%

    layer_bidirectional(

        layer_lstm(

            units =
                lstm_units,

            return_sequences =
                FALSE

        ),

        name =
            "BiLSTM"
    )


###############################################################
# 22. SHARED REPRESENTATION
###############################################################

hidden <-

    x %>%

    layer_dense(

        units =
            dense_units,

        activation =
            "relu",

        name =
            "Shared_Dense"

    ) %>%

    layer_dropout(

        rate =
            dropout_dense,

        name =
            "Shared_Dropout"
    )


###############################################################
# 23. AFFINE FACTOR OUTPUT
###############################################################

factor_output <-

    hidden %>%

    layer_dense(

        units =
            n_factor_outputs,

        activation =
            "linear",

        name =
            "Affine_Factors"
    )


###############################################################
# 24. TREASURY YIELD OUTPUT
###############################################################

yield_output <-

    hidden %>%

    layer_dense(

        units =
            32L,

        activation =
            "relu",

        name =
            "Yield_Hidden"

    ) %>%

    layer_dense(

        units =
            n_yield_outputs,

        activation =
            "linear",

        name =
            "Affine_Pricing"
    )


###############################################################
# 25. VOLATILITY OUTPUT
###############################################################

vol_output <-

    hidden %>%

    layer_dense(

        units =
            32L,

        activation =
            "relu",

        name =
            "Volatility_Hidden"

    ) %>%

    layer_dense(

        units =
            1L,

        activation =
            "softplus",

        name =
            "Volatility"
    )


###############################################################
# 26. CREATE MODEL
###############################################################

cat(
    "Creating Keras model...\n"
)

model <-

    keras_model(

        inputs =
            inputs,

        outputs =
            list(

                Affine_Factors =
                    factor_output,

                Affine_Pricing =
                    yield_output,

                Volatility =
                    vol_output
            ),

        name =
            "Deep_Affine_Transformer_Model"
    )


###############################################################
# 27. MODEL SUMMARY
###############################################################

cat("\n")
cat("============================================================\n")
cat("MODEL SUMMARY\n")
cat("============================================================\n")

summary(model)


###############################################################
# 28. CUSTOM LOSS FUNCTIONS
###############################################################

factor_loss <-

    function(
        y_true,
        y_pred
    ) {

        error <-
            y_true - y_pred

        tf$reduce_mean(
            tf$square(error)
        )
    }


###############################################################

yield_loss <-

    function(
        y_true,
        y_pred
    ) {

        error <-
            y_true - y_pred

        tf$reduce_mean(
            tf$square(error)
        )
    }


###############################################################

volatility_loss <-

    function(
        y_true,
        y_pred
    ) {

        error <-
            y_true - y_pred

        tf$reduce_mean(
            tf$square(error)
        )
    }


###############################################################
# 29. COMPILE MODEL
###############################################################

cat("\n")
cat("============================================================\n")
cat("COMPILING MODEL\n")
cat("============================================================\n")

model %>%

    compile(

        optimizer =

            optimizer_adam(

                learning_rate =
                    learning_rate
            ),

        loss = list(

            Affine_Factors =
                factor_loss,

            Affine_Pricing =
                yield_loss,

            Volatility =
                volatility_loss
        ),

        loss_weights = list(

            Affine_Factors =
                lambda_FACTOR,

            Affine_Pricing =
                lambda_YIELD,

            Volatility =
                lambda_VOL
        ),

        metrics = list(

            Affine_Factors =
                list("mae"),

            Affine_Pricing =
                list("mae"),

            Volatility =
                list("mae")
        )
    )


###############################################################
# 30. FORWARD PASS TEST
###############################################################

cat("\n")
cat("============================================================\n")
cat("FORWARD PASS TEST\n")
cat("============================================================\n")

test_batch <-

    min(
        2L,
        dim(X_train)[1]
    )


###############################################################
# IMPORTANT:
#
# Keep the sequence structure:
#
# batch x time x features
#
# Do NOT convert X_demo to a 2-D matrix.
#
###############################################################

X_demo <-

    X_train[
        seq_len(test_batch),
        ,
        ,
        drop = FALSE
    ]


###############################################################
# Prediction
###############################################################

demo_output <-

    predict(

        model,

        X_demo,

        verbose = 0
    )


###############################################################
# 31. CHECK OUTPUT DIMENSIONS
###############################################################

cat("\n")
cat("Factor output dimensions:\n")

print(
    dim(
        demo_output[[1]]
    )
)


cat("\n")
cat("Yield output dimensions:\n")

print(
    dim(
        demo_output[[2]]
    )
)


cat("\n")
cat("Volatility output dimensions:\n")

print(
    dim(
        demo_output[[3]]
    )
)


###############################################################
# Factor output check
###############################################################

if (

    dim(demo_output[[1]])[1] != test_batch ||

    dim(demo_output[[1]])[2] != n_factor_outputs

) {

    stop(
        paste0(
            "Incorrect affine-factor output dimensions.\n",
            "Expected: ",
            test_batch,
            " x ",
            n_factor_outputs,
            "\nFound: ",
            paste(
                dim(demo_output[[1]]),
                collapse = " x "
            )
        )
    )
}


###############################################################
# Yield output check
###############################################################

if (

    dim(demo_output[[2]])[1] != test_batch ||

    dim(demo_output[[2]])[2] != n_yield_outputs

) {

    stop(
        paste0(
            "Incorrect Treasury-yield output dimensions.\n",
            "Expected: ",
            test_batch,
            " x ",
            n_yield_outputs,
            "\nFound: ",
            paste(
                dim(demo_output[[2]]),
                collapse = " x "
            )
        )
    )
}


###############################################################
# Volatility output check
###############################################################

if (

    dim(demo_output[[3]])[1] != test_batch ||

    dim(demo_output[[3]])[2] != 1L

) {

    stop(
        paste0(
            "Incorrect volatility output dimensions.\n",
            "Expected: ",
            test_batch,
            " x 1\n",
            "Found: ",
            paste(
                dim(demo_output[[3]]),
                collapse = " x "
            )
        )
    )
}


###############################################################
# 32. SAMPLE PREDICTIONS
###############################################################

factor_demo <-
    demo_output[[1]]

colnames(
    factor_demo
) <-
    factor_names


cat("\n")
cat("Sample affine-factor predictions:\n")

print(
    round(
        factor_demo,
        4
    )
)


###############################################################

yield_demo <-
    demo_output[[2]]

colnames(
    yield_demo
) <-
    yield_names


cat("\n")
cat("Sample Treasury-yield predictions:\n")

print(
    round(
        yield_demo,
        4
    )
)


###############################################################

cat("\n")
cat("Sample volatility predictions:\n")

print(
    round(
        demo_output[[3]],
        4
    )
)


###############################################################
# 33. MODEL PARAMETERS
###############################################################

ModelParameters <-

    list(

        sequence_length =
            sequence_length,

        feature_dim =
            feature_dim,

        n_factors =
            n_factor_outputs,

        n_yields =
            n_yield_outputs,

        factor_names =
            factor_names,

        yield_names =
            yield_names,

        head_size =
            head_size,

        num_heads =
            num_heads,

        ff_dim =
            ff_dim,

        num_transformer_blocks =
            num_transformer_blocks,

        cnn_filters =
            c(
                cnn_filters_1,
                cnn_filters_2
            ),

        cnn_kernel_size =
            cnn_kernel_size,

        lstm_units =
            lstm_units,

        dense_units =
            dense_units,

        dropout_transformer =
            dropout_transformer,

        dropout_cnn =
            dropout_cnn,

        dropout_dense =
            dropout_dense,

        learning_rate =
            learning_rate,

        lambda_FACTOR =
            lambda_FACTOR,

        lambda_YIELD =
            lambda_YIELD,

        lambda_VOL =
            lambda_VOL,

        architecture =
            "Transformer + CNN + BiLSTM + Multi-Output Dense Network",

        factor_model =
            "Level + Slope",

        yield_model =
            "DGS10 + DTB3",

        volatility_target =
            "RMS daily yield change"
    )


###############################################################
# 34. SAVE MODEL PARAMETERS
###############################################################

save(

    ModelParameters,

    file =
        "05_ModelParameters.RData"
)


###############################################################
# 35. SAVE R MODEL
###############################################################

save(

    model,

    file =
        "05D_CompiledModel.RData"
)


###############################################################
# 36. SAVE KERAS 3 MODEL
###############################################################

model_file <-

    "Deep_Affine_Transformer_Compiled.keras"


cat("\n")
cat(
    "Saving Keras 3 model...\n"
)

save_model(

    model,

    model_file,

    overwrite =
        TRUE
)


###############################################################
# 37. VERIFY KERAS MODEL
###############################################################

if (
    !file.exists(model_file)
) {

    stop(
        "Keras model file was not created."
    )
}


###############################################################
# 38. ARCHITECTURE INFORMATION
###############################################################

architecture_info <-

    data.frame(

        Layer = c(

            "Input",
            "Input Projection",
            "Transformer 1",
            "Transformer 2",
            "CNN 1",
            "CNN 2",
            "BiLSTM",
            "Shared Dense",
            "Affine Factors",
            "Affine Pricing",
            "Volatility"

        ),

        Description = c(

            paste0(
                sequence_length,
                " x ",
                feature_dim
            ),

            paste0(
                feature_dim,
                "-dimensional projection"
            ),

            paste0(
                "Multi-head attention: ",
                num_heads,
                " heads x ",
                head_size
            ),

            paste0(
                "Multi-head attention: ",
                num_heads,
                " heads x ",
                head_size
            ),

            paste0(
                cnn_filters_1,
                " filters, kernel size ",
                cnn_kernel_size
            ),

            paste0(
                cnn_filters_2,
                " filters, kernel size ",
                cnn_kernel_size
            ),

            paste0(
                lstm_units,
                " units per direction"
            ),

            paste0(
                dense_units,
                "-unit representation"
            ),

            paste(
                factor_names,
                collapse = ", "
            ),

            paste(
                yield_names,
                collapse = ", "
            ),

            "Positive volatility output"

        ),

        stringsAsFactors =
            FALSE
    )


###############################################################
# 39. EXPORT ARCHITECTURE
###############################################################

write.csv(

    architecture_info,

    "05_ModelArchitecture.csv",

    row.names =
        FALSE
)


###############################################################
# 40. SAVE OUTPUT NAMES
###############################################################

OutputNames <-

    list(

        factor_names =
            factor_names,

        yield_names =
            yield_names,

        volatility_name =
            "Volatility"
    )


save(

    OutputNames,

    file =
        "05D_OutputNames.RData"
)


###############################################################
# 41. FINAL VALIDATION
###############################################################

if (
    sequence_length != 20L
) {

    warning(
        paste0(
            "Sequence length is ",
            sequence_length,
            ", not 20."
        )
    )
}


if (
    feature_dim != 55L
) {

    warning(
        paste0(
            "Feature dimension is ",
            feature_dim,
            ", not 55."
        )
    )
}


if (
    n_factor_outputs != 2L
) {

    stop(
        "The model requires exactly two affine factors: Level and Slope."
    )
}


if (
    n_yield_outputs != 2L
) {

    stop(
        "The model requires exactly two Treasury yields: DGS10 and DTB3."
    )
}


if (
    !identical(
        factor_names,
        c(
            "Level",
            "Slope"
        )
    )
) {

    stop(
        "Affine factor ordering is incorrect."
    )
}


if (
    !identical(
        yield_names,
        c(
            "DGS10",
            "DTB3"
        )
    )
) {

    stop(
        "Yield ordering is incorrect."
    )
}


###############################################################
# 42. FINAL SUMMARY
###############################################################

cat("\n")
cat("============================================================\n")
cat("05D COMPILE MODEL COMPLETED SUCCESSFULLY\n")
cat("============================================================\n")

cat(
    "Input              : ",
    sequence_length,
    " time steps x ",
    feature_dim,
    " predictors\n",
    sep = ""
)

cat(
    "Training sequences : ",
    dim(X_train)[1],
    "\n",
    sep = ""
)

cat(
    "Validation sequences: ",
    dim(X_valid)[1],
    "\n",
    sep = ""
)

cat(
    "Testing sequences  : ",
    dim(X_test)[1],
    "\n",
    sep = ""
)

cat(
    "Affine factors     : ",
    paste(
        factor_names,
        collapse = ", "
    ),
    "\n",
    sep = ""
)

cat(
    "Treasury yields    : ",
    paste(
        yield_names,
        collapse = ", "
    ),
    "\n",
    sep = ""
)

cat(
    "Volatility target  : RMS daily yield change\n"
)

cat(
    "Transformer blocks : ",
    num_transformer_blocks,
    "\n",
    sep = ""
)

cat(
    "Attention heads    : ",
    num_heads,
    "\n",
    sep = ""
)

cat(
    "CNN filters        : ",
    paste(
        c(
            cnn_filters_1,
            cnn_filters_2
        ),
        collapse = ", "
    ),
    "\n",
    sep = ""
)

cat(
    "BiLSTM units       : ",
    lstm_units,
    " per direction\n",
    sep = ""
)

cat(
    "Learning rate      : ",
    learning_rate,
    "\n",
    sep = ""
)

cat(
    "Factor loss weight : ",
    lambda_FACTOR,
    "\n",
    sep = ""
)

cat(
    "Yield loss weight  : ",
    lambda_YIELD,
    "\n",
    sep = ""
)

cat(
    "Volatility weight  : ",
    lambda_VOL,
    "\n",
    sep = ""
)

cat("\n")

cat(
    "Keras model        : ",
    model_file,
    "\n",
    sep = ""
)

cat(
    "R model            : 05D_CompiledModel.RData\n"
)

cat(
    "Parameters         : 05_ModelParameters.RData\n"
)

cat(
    "Architecture       : 05_ModelArchitecture.csv\n"
)

cat(
    "Output names       : 05D_OutputNames.RData\n"
)

cat("\n")

cat(
    "05D_compile_model.R completed successfully.\n"
)

cat("============================================================\n")